SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (1, 'a_ikchurin', 'tyoma11.95@mail.ru', 100283, NULL, '$2a$10$TzL5Fv8aBrROhXdJM1/wE.6aokRkYMhhZbcfE859z/CvQYYr5Clzm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (2, 'cvkucherov', 'cvkucherov@yandex.ru', 53851, NULL, '$2a$10$NUn3CE0LdELX4.HXHHR0EOkLpSzoBYTvfiZ5hVjPfLMHW3YCAn7lS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (3, 'gabolaev', 'gabolaev98@gmail.com', 76791, NULL, '$2a$10$kTiGiYzVLiCDEaE2buB9ne6hjrFS16FCprZ2CwlO48MSvSf2Odm6S');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (4, 'venger', 'farir1408@gmail.com', 68925, NULL, '$2a$10$.yCz8O1slqKre7SxEQY6Yusa9DuwMu.9.NwjDRkYnPuktDKhe9mH.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (5, 'a.ostapenko', 'a.ostapenko@corp.mail.ru', 100500, 'https://park.mail.ru/media/avatars/gtp/12/03/87f4d79e36d68c3031ccf6c55e9bbd39.jpg', '$2a$10$BfUIXs3iZmfWU8CFMDnWc.n6IbCeFUALNiMH6YB1PLDzPYzqXK1ki');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (6, 'd.dorofeev', 'd.dorofeev@corp.mail.ru', 100500, 'https://park.mail.ru/media/avatars/11/17/58d4d1e7b1e97b258c9ed0b37e02d087.jpg', '$2a$10$9aTPXi/FIOyGBvRYgZHe..c0nOmPBuRJEROXDF07dfjfjXOeI/JRK');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (7, 'marina.titova', 'marina.titova@corp.mail.ru', 100500, 'https://park.mail.ru/media/avatars/gtp/02/17/4079016d940210b4ae9ae7d41c4a2065_AQBGC0E.jpg', '$2a$10$.9THZn9M9eSqmIv40sbOAuAv2OHD8GQB4yaneePnOlVlc88AzVU4a');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (8, 'a.tyuldyukov', 'a.tyuldyukov@corp.mail.ru', 100500, 'https://park.mail.ru/media/avatars/gtp/02/23/2e7ceec8361275c4e31fee5fe422740b.jpg', '$2a$10$B9UO.UDPEYp4YklZZJBwX.5K7xrXtcl8hLlL8u50P5J2QIYTcWmLm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (9, 'lina.paucek', 'lina.paucek@hotmail.com', 5614, NULL, '$2a$10$SD0OXFe.Gz4TkmvjBjxIcuN/r4fzEVw7rwSIJjB.RMR8U8m0PjRdi');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (10, 'hyman.wyman', 'hyman.wyman@gmail.com', 37015, NULL, '$2a$10$zxRGi063mtgSLf6WiEuSY.OqntZBoRimNjwpSP4nFuUsLTXv9l8uC');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (11, 'corbin.bashirian', 'corbin.bashirian@hotmail.com', 90866, NULL, '$2a$10$4I7mn..0a6g16s.9xd8hper9YGXWlzu43.Mf7aFii7ZBu4/5Rujla');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (12, 'earnest.ullrich', 'earnest.ullrich@gmail.com', 76442, NULL, '$2a$10$OoFkoGP5h1xexweOoyi36e1goKwwxWGIrhZ7dmLJvRYmCw9HppkLO');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (13, 'viva.vonrueden', 'viva.vonrueden@yahoo.com', 22690, NULL, '$2a$10$/eTfO7JisBXcji2dOFHjhOpkF0cszq.B.zfCfa3Os92FvZNom5fx2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (14, 'liana.weber', 'liana.weber@yahoo.com', 58420, NULL, '$2a$10$j33Jj6CNmvH.AFIWCMgEq.WwnkcYugymEPQdbpgXEG5FYqd9mr8nu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (15, 'araceli.bogan', 'araceli.bogan@gmail.com', 27229, NULL, '$2a$10$O0H8Kd27rZplEgRKxfqx8e62OqJnjHB7Iwel7E6QP1zBtJsXbps4a');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (16, 'merlin.hintz', 'merlin.hintz@yahoo.com', 48119, NULL, '$2a$10$fSya/qfRd4RfhsKrkUaIIOXJNbfp55dNNYYYbhWU45GeToi3.Xrka');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (17, 'kaylie.mraz', 'kaylie.mraz@gmail.com', 11229, NULL, '$2a$10$W7XS/HhiQd5x/OKWLolQqO9H0C9CJ396ocabzcPAWaE7T3hDPDr/W');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (18, 'natasha.price', 'natasha.price@hotmail.com', 74957, NULL, '$2a$10$7BsIagOpnsjkf3inQF6aveWStwC4.EBKQQr7BuJrNc0T2M5vadh9G');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (19, 'jaylen.monahan', 'jaylen.monahan@yahoo.com', 55618, NULL, '$2a$10$7UhqKMbkgFwXXH5enG6lsuAb61FDvZieH9Scyz8txQy3c50qZI.02');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (20, 'tressie.damore', 'tressie.damore@hotmail.com', 55641, NULL, '$2a$10$39Vy0WucjIw2lzsti54zTeSP1v3bLBlMxD06TUbMXDez5oyAu90Di');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (21, 'sofia.krajcik', 'sofia.krajcik@yahoo.com', 97844, NULL, '$2a$10$rVxpxWAnJHD/EzWD.IpW1.2uBE/Tocm9HQm0IDgj4Nnw00lJtzJw.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (22, 'icie.jakubowski', 'icie.jakubowski@gmail.com', 66975, NULL, '$2a$10$JFfDnH1azILYmo.703aLXOrT96cOrib32tyzWvI0J8FurkDcqWwHu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (23, 'jadyn.goodwin', 'jadyn.goodwin@yahoo.com', 35849, NULL, '$2a$10$sGZsZOXoXQ1AdOntI9SgZ.zZrh4kK1.F51PODR4/lEx5R/Php2TJ2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (24, 'esmeralda.kulas', 'esmeralda.kulas@hotmail.com', 79852, NULL, '$2a$10$0vfbEHXESQBF9iq.4x/S5OhvhvzcU0BOe48J4SI.t.49xVZu9AirS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (25, 'carlee.bashirian', 'carlee.bashirian@yahoo.com', 30420, NULL, '$2a$10$w4JrF5jFn.ZR.93/M7tdAeujFGPUqm2abD7CewTybW7iDwEGGykYq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (26, 'general.davis', 'general.davis@gmail.com', 30102, NULL, '$2a$10$mVsyXe8y6lVPVUkUViuO6eZNI86.lM5NtrhOtrknsK5BooQsrKm6S');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (27, 'garett.hyatt', 'garett.hyatt@yahoo.com', 5834, NULL, '$2a$10$Jpkes/wim6RDSDGW0V0kH.nJGln0.uLrAQ4RxxNxYE4PhZsKXIoTG');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (28, 'romaine.marquardt', 'romaine.marquardt@hotmail.com', 92283, NULL, '$2a$10$/n1Jc76ctXW9nJY489laxul2kZgn9IgiXmNCO1AtOEqKOgjwtQFiq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (29, 'cathy.murazik', 'cathy.murazik@yahoo.com', 96044, NULL, '$2a$10$REU74UfeJeCirWE3v9QSDejXJ7jszEx7kwVn.JDQUvHZ1PDNoJ3Jy');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (30, 'davonte.schinner', 'davonte.schinner@gmail.com', 71186, NULL, '$2a$10$9Psi6q/kkZFmzfF/keGVTuzyrZPSwsfogVohLS1OYTJYPYrq.WukS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (31, 'sonny.towne', 'sonny.towne@hotmail.com', 27351, NULL, '$2a$10$FnN3I2cvV9NSb47zLi.SQebHipPVUvvi/EuDTz6UPxfbS1zQcBeJ6');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (32, 'shanny.skiles', 'shanny.skiles@gmail.com', 81973, NULL, '$2a$10$ovk4peCIjNLqH2fvuM3yXOYE0j.Dy7QN78c80tllkz1UGfp7dxVai');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (33, 'romaine.wiza', 'romaine.wiza@gmail.com', 76923, NULL, '$2a$10$i0WB0vKR9HZNKAACqMtCgu/j6Ed/UmbZHtUeR7xthluqvtDGDLTRK');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (34, 'elyssa.shanahan', 'elyssa.shanahan@hotmail.com', 14453, NULL, '$2a$10$oJeMJlcjfLgDAXSa8oHeXujTL1WzRgy8WbXskBXKhgjfj92rjjwci');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (35, 'malika.renner', 'malika.renner@yahoo.com', 29788, NULL, '$2a$10$JIEaZ.9sMcqi7wFqQywibunQgpuscLZJJf4jaENombXta1mQI8v7O');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (36, 'krista.lockman', 'krista.lockman@hotmail.com', 46214, NULL, '$2a$10$hnTWuWptV9IwVJJNxMMiL.YilqE3EzWYg60AGZC8Plb312sSVL7ua');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (37, 'charlotte.mills', 'charlotte.mills@gmail.com', 97820, NULL, '$2a$10$JZ9FJHNOwIzywXPmWRvkwOY9K9uize7SxazeDKbDRIEUaiPsg5NZW');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (38, 'alisha.grady', 'alisha.grady@yahoo.com', 82792, NULL, '$2a$10$h.FzjPaMBzKtHgKFoUK5P.hvwwSroY/lTa02ONhmv5H9M/64bdfw6');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (39, 'birdie.cronin', 'birdie.cronin@hotmail.com', 66959, NULL, '$2a$10$OZuMZ/ZltIY/3fbYzwNl2unkgI5BM6TB4NMUk77xwC6ZB80LCb2lS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (40, 'ramiro.pollich', 'ramiro.pollich@yahoo.com', 8509, NULL, '$2a$10$H88.PFObVs1seaQimT2oIOo7.tAtXa7sQoN9Yo7tsLVlRgYRFjSNW');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (41, 'sebastian.quigley', 'sebastian.quigley@gmail.com', 30130, NULL, '$2a$10$oRToqCz5r7Xc4KJ3c98rh.WPeGCj8kblZAv80IXN5BfrR/2itis9i');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (42, 'khalid.legros', 'khalid.legros@hotmail.com', 1834, NULL, '$2a$10$SXmq.KQITXKybMsduaKu/u0fvmHrA..FFflTbmlWURavLyNZ0Y7Y.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (43, 'constantin.waters', 'constantin.waters@hotmail.com', 7799, NULL, '$2a$10$qnek78Svp16H/6aMeLIBCeSfNpdsOx04OPoIqO6SD.fQoMVZRgW9m');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (44, 'giovanny.bogan', 'giovanny.bogan@yahoo.com', 37705, NULL, '$2a$10$2SkAVZpFR.I9NURIJ3nDdufrwYpOMAj7U5hBEooqlAygFQlDB7ATq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (45, 'giovanna.brown', 'giovanna.brown@hotmail.com', 53467, NULL, '$2a$10$paE6wb05ZrT3iJkDETDAKOtqRC6nBcs68mNQXXqWJLg.JE.ZD5ekG');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (46, 'ernestina.barton', 'ernestina.barton@yahoo.com', 4816, NULL, '$2a$10$hSmDd9wqF9ONgmiT8Py6o.UZzQ4YyZBNaF/A8gl.Qb.sk0XhfmiR2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (47, 'brenden.mayer', 'brenden.mayer@yahoo.com', 99104, NULL, '$2a$10$S4hn7KFUXOoWJvH6bRswUeOuJ414iyaY1SkVl7/ifoofX.rVCaJBu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (48, 'kailee.wiegand', 'kailee.wiegand@gmail.com', 40815, NULL, '$2a$10$S0ds56fG1NOX5hKFNAFm/eddXOgm4bR6ir3MGm.hgXvS0r9broRFy');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (49, 'quinton.johnston', 'quinton.johnston@hotmail.com', 26269, NULL, '$2a$10$mNMQ5V2nnSQ2PBLszbYGGekQP7ku7Q8f5Rq/6Lfmxv.cvRXWL2Gmq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (50, 'joelle.hegmann', 'joelle.hegmann@yahoo.com', 54603, NULL, '$2a$10$f9W4pP1yfAtlsUlgfYbmYeM170G1T2W3ldMQkpJcnCucS7oZFODNG');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (51, 'skylar.stehr', 'skylar.stehr@gmail.com', 62179, NULL, '$2a$10$XKsa0bjux6IYH2nryKLw1uPhjEf/UOO.XibGHmr5GEL5Ib7N8Qjay');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (52, 'gustave.sawayn', 'gustave.sawayn@yahoo.com', 49226, NULL, '$2a$10$E5BMXty9XOXgBGlCaeq5aOooWfzbQA9ZwWM6PZErrr22ZXkHq0Ijm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (53, 'kira.lockman', 'kira.lockman@gmail.com', 56829, NULL, '$2a$10$IzPw.0aLbcCgand1vLLuPeEoabyU.0UaSl19jCQx42J/qLm7JQY9S');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (54, 'wilma.spinka', 'wilma.spinka@gmail.com', 14824, NULL, '$2a$10$zn3R46papeasbZWF/xL5.OhoX4aD2Y9zwGIl4yY3bJgo.IkKGv4dC');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (55, 'fletcher.rau', 'fletcher.rau@yahoo.com', 28296, NULL, '$2a$10$AgVGAAp/PNjyWe7vrJPJdOHGvby2hqqQl1E.ybAc8Qhj5iIXidGTS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (56, 'joseph.bashirian', 'joseph.bashirian@yahoo.com', 95773, NULL, '$2a$10$zirlEHQkq4T.TpXEBc1XkOkEqsXcNZxBwE/moROkRTuZizuLwbyc2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (57, 'roscoe.labadie', 'roscoe.labadie@hotmail.com', 7648, NULL, '$2a$10$36HHrsogfUY0gClWhe8H.O8DYPeRzE7HLy/P607W3e2pU7RbETD3O');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (58, 'norwood.boyle', 'norwood.boyle@gmail.com', 30077, NULL, '$2a$10$Xxugfz7KBInTLTAhRtVAd.mvC8Bztpsrt4hqtsYOqfHMRSXGA7BDC');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (59, 'karl.spencer', 'karl.spencer@hotmail.com', 27270, NULL, '$2a$10$XagOianAwMwZaZWFyJpD7urh6u.3pC/3B21sFVAadmevEmLaIZZN6');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (60, 'gudrun.will', 'gudrun.will@yahoo.com', 28182, NULL, '$2a$10$FZQj.lpYAUeAAxj10ZbZK.KiSYyRcfatbsVZwdgy7OWLfNmsP4w4a');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (61, 'antonetta.hessel', 'antonetta.hessel@gmail.com', 63871, NULL, '$2a$10$nO1PyUFWLNbzBiBX2aYxIurp5N5j8ZfNgJjJA/C4Y.bPoO/4tNkzS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (62, 'lucy.kovacek', 'lucy.kovacek@yahoo.com', 85974, NULL, '$2a$10$IkjQOainLbTCBzGmdsu8Zew21Ios.q0UFlgSM6OAjhlHyjeIImj4.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (63, 'genesis.littel', 'genesis.littel@yahoo.com', 9752, NULL, '$2a$10$o57DiD/CziG/k6oDF8WkYubIYxTLluf54MGjnSlB7C3JXYfKalm9S');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (64, 'quincy.dickinson', 'quincy.dickinson@hotmail.com', 98135, NULL, '$2a$10$.ZuopvWTOudrW3LIjLfZ.O5OpfpMDf9jCZpO5Zu1LAi5HjkALYZSC');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (65, 'ambrose.watsica', 'ambrose.watsica@hotmail.com', 11302, NULL, '$2a$10$7nWmMFUB8kRFZCj6kLYe0O0dkWxIiFukaZ0zNj8ne/zfpDn/k5zne');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (66, 'narciso.ward', 'narciso.ward@hotmail.com', 57979, NULL, '$2a$10$nFqGMxz3xFGruy5ZwKNSZOXk7Di7WQSGjLKk/525k.EM/CocRhF7C');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (67, 'alison.botsford', 'alison.botsford@yahoo.com', 65023, NULL, '$2a$10$9Ch4cvZn6KFrNSFg3nTqiedBmSBGxD8kvF//dYSoBQduAUgRq3oSu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (68, 'otis.bergstrom', 'otis.bergstrom@yahoo.com', 66667, NULL, '$2a$10$xH9irATRB2oCuUICrxAFkuNALkAmMpfVoN9fYbwrzOz1qlTaR/YZm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (69, 'benton.kassulke', 'benton.kassulke@hotmail.com', 64229, NULL, '$2a$10$8NAniCdfhusH80hAOT1aPOQlN27GTMerYGu3BAUutFS3sDjHqnBp.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (70, 'april.wehner', 'april.wehner@yahoo.com', 19729, NULL, '$2a$10$D6KNU6Hpc9KtyrsxtxRs6O0M4n3XBm/ow50rtMuegQvUqR/rYaaZ.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (71, 'alexandro.rice', 'alexandro.rice@hotmail.com', 71879, NULL, '$2a$10$ZBhjumocx380E63SMBJ1L.aLVhtSw6PzXqo5K0mZLaZgpnn7sga0u');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (72, 'sibyl.stiedemann', 'sibyl.stiedemann@gmail.com', 16576, NULL, '$2a$10$SYQtOv.o3BcoYg5PqkU2CeNmrIOxJ.6wk/q0yRdUGIm9fp.qpsoy6');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (73, 'ursula.terry', 'ursula.terry@hotmail.com', 46155, NULL, '$2a$10$jcEh1Uv/F0N0znV.pi5kl.ZStNWN7ggk9p5VKucB2edJAJ2E5nEbq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (74, 'arnulfo.kub', 'arnulfo.kub@hotmail.com', 91013, NULL, '$2a$10$7pL0kkDu.gr1cu4mwAQ4suqJFsn5E46WZ6rwFuERA30VJ9FuqPtiG');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (75, 'alessandra.cruickshank', 'alessandra.cruickshank@yahoo.com', 30386, NULL, '$2a$10$TRvRmeKCxac6iDbO3HaLGuJTePJn6CshEyyfb9kIIxyt2aZls.Y3C');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (76, 'demarcus.doyle', 'demarcus.doyle@gmail.com', 83840, NULL, '$2a$10$N8xZlUTklATOFOH3hMGkV.Dta.sWDdztzTBATeZQ3g0jLj/lmME0O');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (77, 'tanya.heaney', 'tanya.heaney@yahoo.com', 51049, NULL, '$2a$10$/LwineFhdCsaVFbIaSmjiuqzxqMugMwCdXo0InTp/GdtokrRt5EDu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (78, 'jose.schulist', 'jose.schulist@hotmail.com', 93832, NULL, '$2a$10$M1/3OamxrpjW0VI1cO51qOd4CuhxloXtZ5N6/DvgdWya6rzKS99XW');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (79, 'christine.paucek', 'christine.paucek@yahoo.com', 43443, NULL, '$2a$10$QIl9uN.QolO0WueEhMkTtOHPrki.CXthnriqFqRMTpf8FBpoC3SKq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (80, 'jennifer.grady', 'jennifer.grady@hotmail.com', 21123, NULL, '$2a$10$KEpmkgto1tKFccEiWn2UE.8.YX7PHij7Nvd0QYul/ymyFRYoFzKPe');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (81, 'zechariah.grimes', 'zechariah.grimes@hotmail.com', 24840, NULL, '$2a$10$sscnNt2HX9bmjOKrrlrOfOQIbjYxeGLIeM30J7GWzK2xVvrFHUfhi');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (82, 'santina.beer', 'santina.beer@gmail.com', 62553, NULL, '$2a$10$LlB2zp79LIo25yW/.fHWVuNfXAJjLQcezCezcWRHR4.3xCEEFIZzi');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (83, 'toy.altenwerth', 'toy.altenwerth@yahoo.com', 82620, NULL, '$2a$10$iZawmkq0oKGlFlYlqYEk5e7rXodF1zgkESzg8K5NgBZC/8g8FzJPa');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (84, 'charlene.muller', 'charlene.muller@yahoo.com', 80923, NULL, '$2a$10$..Ze73k2rBmuv4GqiWbLAOj24mRNlSptdDEzesBpHOJSioLcP6fY.');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (85, 'cheyenne.bartoletti', 'cheyenne.bartoletti@gmail.com', 71963, NULL, '$2a$10$WiWEb8vzWm5BNzp0E/YkG./lLMVmi8TMqf3sChLk.xZ4OShz63a16');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (86, 'elda.jaskolski', 'elda.jaskolski@gmail.com', 7666, NULL, '$2a$10$7ETK4QdSDdVmh4au5JFmru52t.2HhGPLhN98cCWaYMB8DbzO5hape');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (87, 'zane.mueller', 'zane.mueller@hotmail.com', 68909, NULL, '$2a$10$3P0vjM9.U8lM/HYihuBMSONovt3f7oYDtU4m07IQ.XI7Z3VVdRxDm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (88, 'virgie.kuhn', 'virgie.kuhn@hotmail.com', 19323, NULL, '$2a$10$OBXblcrodTPrArT1c7j0qeqp.ZN4ReHGLGxP4tR60nMD1o/lcCTmC');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (89, 'karl.hansen', 'karl.hansen@gmail.com', 58171, NULL, '$2a$10$eb/AZUmefRX.fcrm9dPHdezbac3eUOCuQyl.gwd7YB524c6OQ/JB2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (90, 'vernice.lesch', 'vernice.lesch@yahoo.com', 61538, NULL, '$2a$10$WTYZLh8lNzYsK4DwqU25dezAa4mf9oIJo.1SVcSZe0txA/n3pzqUu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (91, 'giovanni.smith', 'giovanni.smith@hotmail.com', 83066, NULL, '$2a$10$qMWDLLQ9l2jHgM0HnaC71.btJHiLSo5cycLYLMWwoMyGJg.UgP6PS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (92, 'maybell.morar', 'maybell.morar@hotmail.com', 35090, NULL, '$2a$10$mmpXLOOW9NbqKyNd.Up4sO6Yb2Pq3//M/s5Q.E2KL.2btInTy0h6i');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (93, 'delbert.bogisich', 'delbert.bogisich@gmail.com', 15364, NULL, '$2a$10$uEG0ZAT0GiKDGswITLJdz.BnKRT6ZzQJS0vtwjGG5pf7bkJj80vqq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (94, 'abdullah.hansen', 'abdullah.hansen@yahoo.com', 22132, NULL, '$2a$10$LPcm3C7PuLe3WCjULTarq.mfkplyK5O2UleWq2KlkUicNaGadIP4W');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (95, 'demond.okuneva', 'demond.okuneva@yahoo.com', 80087, NULL, '$2a$10$SOjErcSWPJsmM.2wo2lQ.ufdYT.vywxQnAVv6LUAMFhc5/byIXhjW');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (96, 'isom.ondricka', 'isom.ondricka@gmail.com', 46812, NULL, '$2a$10$KvsxJ6F1oVYlRdad9YbucOaoR9KBqPxscR4O3ffqCEG3BgXYa0zSe');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (97, 'abelardo.leuschke', 'abelardo.leuschke@yahoo.com', 48345, NULL, '$2a$10$qjPuhSCTZDom5Wo0RvG7PeUrtVwh36r6JPnmD8guQCDNK8NQp3lbq');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (98, 'shad.emard', 'shad.emard@gmail.com', 97564, NULL, '$2a$10$3IirgloBYMkQ9ShDO4LsG.rUMZNAuP9F48DvyHLHIqSzsD0Nozcn2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (99, 'belle.rohan', 'belle.rohan@yahoo.com', 56678, NULL, '$2a$10$epd.GTkXLQExgia/DtFaNuA2ikg6agEqq2TKTiOni50Cqb2e15Cwm');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (100, 'armani.stehr', 'armani.stehr@hotmail.com', 76082, NULL, '$2a$10$iuEfpOl0nVgaIbbrFPnDYue7aNK2CIPx4G0YibPs96VOS2VXHvLfu');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (101, 'jessica.walter', 'jessica.walter@gmail.com', 87461, NULL, '$2a$10$4gHNyr4Y1Oa0PUs2QEmpG.KM8MIF/dMuw.hySlqd/uAEv5xKAvE9G');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (102, 'bobbie.schinner', 'bobbie.schinner@gmail.com', 84223, NULL, '$2a$10$jgMt4LtqgjaF7/Bqv6ng9OdLZQU07th.Il22dFtGkl6E2CGJhjnpe');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (103, 'shyanne.beatty', 'shyanne.beatty@hotmail.com', 67229, NULL, '$2a$10$dLjGknpavjdmmaZaeAZYsuA5Ohssjcnrpw5Cc93qlLQOjE4kzLGXS');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (104, 'waino.swaniawski', 'waino.swaniawski@gmail.com', 29787, NULL, '$2a$10$dOqwW2Lay4OC3UuHP8mAlu4TK3SbuHby7RXZPxSSDK8REENzMEGJa');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (105, 'cesar.bogan', 'cesar.bogan@yahoo.com', 48834, NULL, '$2a$10$5S/Hw/qDzONa9U4KcuX.P.mEK7oUs5qcNtJd7ZQspMQeHaJV.cTiG');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (106, 'aaliyah.volkman', 'aaliyah.volkman@gmail.com', 70160, NULL, '$2a$10$IacwISkmBI4BP8WyNOYwMeTT4C4WcERBOPNxVULDBU7X7uTIUKMZ2');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (107, 'casimer.douglas', 'casimer.douglas@yahoo.com', 80803, NULL, '$2a$10$kj8rkDr.mNRFw/sLk4bWAelof6bNie5ojtWqHwdoPU1/d94.t5VGW');
INSERT INTO public.users (id, username, email, rank, avatar_link, password) VALUES (108, 'scottie.tromp', 'scottie.tromp@yahoo.com', 54079, NULL, '$2a$10$dfohZRIFl9RdEvMBV3sU8ui8snSMWlS3XAOrpr3lK.iFE9s2ReYwG');
